# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-01 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tak_priority',
            new_name='task_priority',
        ),
    ]
